#!/usr/bin/env python3
"""Build compact category retrieval indexes from existing Markdown files."""

from __future__ import annotations

import argparse
from pathlib import Path
from lookup_knowledge import sections


CATEGORY_ROUTES: dict[str, list[tuple[str, str]]] = {
    "ctf-ai-ml": [("adversarial inputs, perturbations", "adversarial-ml.md"), ("model extraction or inversion", "model-attacks.md"), ("LLM, prompt, or LoRA attacks", "llm-attacks.md")],
    "ctf-crypto": [("RSA, modulus, signatures", "rsa-attacks.md"), ("AES, modes, MACs, oracles", "modern-ciphers.md"), ("LWE, HNP, short errors", "lattice-and-lwe.md"), ("PRNG or predictable state", "prng.md"), ("ECC or nonce reuse", "ecc-attacks.md")],
    "ctf-forensics": [("PCAP, protocol, timing", "network.md"), ("disk or memory image", "disk-and-memory.md"), ("image steganography", "stego-image.md"), ("audio or signal", "stego-advanced.md"), ("Windows artifacts", "windows.md")],
    "ctf-malware": [("obfuscated script or shellcode", "scripts-and-obfuscation.md"), ("C2 traffic or encrypted protocol", "c2-and-protocols.md"), ("PE, .NET, or config extraction", "pe-and-dotnet.md")],
    "ctf-misc": [("Python jail", "pyjails.md"), ("restricted shell", "bashjails.md"), ("encoding or QR", "encodings.md"), ("RF or SDR", "rf-sdr.md"), ("game, toy VM, or constraint", "games-and-vms.md")],
    "ctf-osint": [("social media or username", "social-media.md"), ("image geolocation or landmark", "geolocation-and-media.md"), ("DNS, archive, public web", "web-and-dns.md")],
    "ctf-pwn": [("stack overflow or ret2win", "overflow-basics.md"), ("ROP or shellcode", "rop-and-shellcode.md"), ("format string", "format-string.md"), ("heap allocator", "heap-techniques.md"), ("kernel target", "kernel.md")],
    "ctf-reverse": [("tool selection and static triage", "tools.md"), ("dynamic hooks or symbolic execution", "tools-dynamic.md"), ("anti-debug or anti-VM", "anti-analysis.md"), ("custom VM or transform", "patterns.md"), ("language or framework", "languages.md")],
    "ctf-web": [("SQL injection", "sql-injection.md"), ("SSTI, SSRF, LFI", "server-side.md"), ("upload or execution", "server-side-exec.md"), ("XSS, CSP, admin bot", "client-side.md"), ("JWT, OAuth, authz", "auth-and-access.md")],
}


def headings(path: Path, limit: int | None = None) -> list[str]:
    found = [section['title'] for section in sections(path) if section['level'] == 2 and section['title'].casefold() not in {'table of contents', 'references'}]
    return found if limit is None else found[:limit]


def build_index(root: Path, category: str) -> str:
    directory = root / category
    lines = [
        f"# {category} Retrieval Index",
        "",
        "<!-- Generated by scripts/rebuild_indexes.py; do not hand-edit. -->",
        "Use this index after category selection. Open only the reference whose signal matches the current hypothesis.",
        "",
        "## High-signal routes",
        "",
        "| Evidence or symptom | Start with |",
        "|---|---|",
    ]
    for signal, filename in CATEGORY_ROUTES[category]:
        if (directory / filename).is_file():
            lines.append(f"| {signal} | [{filename}]({filename}) |")
    lines.extend(["", "## Targeted retrieval", "",
        f"Run `python3 <bundle>/scripts/lookup_knowledge.py '<evidence>' --category {category} --limit 5`.",
        "Results include exact section lines. Read that range before loading another reference.",
        "Start modern parser/runtime cases with [modern-playbook.md](modern-playbook.md); preserve earlier variants in the catalog.",
        "", "## File catalog", ""])
    for path in sorted(directory.rglob("*.md"), key=lambda item: item.relative_to(directory).as_posix().casefold()):
        if path.name in {"INDEX.md", "SKILL.md"}:
            continue
        topics = headings(path)
        # All sections remain searchable; the index stays compact even for long references.
        summary = "; ".join(topics[:3]) if topics else "Supporting category knowledge"
        if len(topics) > 3:
            summary += f"; {len(topics) - 3} further searchable sections"
        relative = path.relative_to(directory).as_posix()
        lines.append(f"- [{relative}]({relative}) — {summary}")
    lines.extend([
        "",
        "## Cross-category pivots",
        "",
        "- Native artifact plus confirmed memory-corruption primitive: reverse first, then pwn.",
        "- Encrypted material recovered from packets or disk: forensics first, then crypto.",
        "- Custom cipher implemented inside a binary: reverse primary, crypto secondary.",
        "- Image hidden payload: forensics; image landmark identification: OSINT.",
        "- HTTP app whose core blocker is binary or crypto logic: keep web primary only while the HTTP trust boundary remains decisive.",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = args.root.resolve()
    stale: list[str] = []
    for category in CATEGORY_ROUTES:
        destination = root / category / "INDEX.md"
        content = build_index(root, category)
        if args.check:
            if not destination.is_file() or destination.read_text(encoding="utf-8") != content:
                stale.append(destination.relative_to(root).as_posix())
        else:
            destination.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        print("stale indexes: " + ", ".join(stale))
        return 1
    print("category indexes are current" if args.check else f"rebuilt {len(CATEGORY_ROUTES)} category indexes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
